# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spacetagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "Google-Mobile-Ads-SDK"
  pod "PKHUD", "~> 5.0"
  pod "Fabric"
  pod "Crashlytics"
  pod "Comets"

end
